### ISSUE TITLE
Failed to compile in 0.21.1

### ISSUE THREAD

**Issue by Piplopp** [OpenGene/fastp#348]
Hello,

The latest commit seems to have added a bug in the compilation. I am not familiar with cpp so I have no clue what's happening, I've attached the error and the g++ version below.

```bash
g++ -c src/stats.cpp -o obj/stats.o -std=c++11 -g -O3 -I./inc  
g++ -c src/htmlreporter.cpp -o obj/htmlreporter.o -std=c++11 -g -O3 -I./inc  
In file included from src/htmlreporter.cpp:1:
src/htmlreporter.h:20:24: error: ‘atomic_long’ has not been declared
     void setInsertHist(atomic_long* insertHist, int insertSizePeak);
                        ^~~~~~~~~~~
In file included from src/htmlreporter.cpp:1:
src/htmlreporter.h:42:5: error: ‘atomic_long’ does not name a type
     atomic_long* mInsertHist;
     ^~~~~~~~~~~
src/htmlreporter.cpp:22:34: error: variable or field ‘setInsertHist’ declared void
 void HtmlReporter::setInsertHist(atomic_long* insertHist, int insertSizePeak) {
                                  ^~~~~~~~~~~
src/htmlreporter.cpp:22:34: error: ‘atomic_long’ was not declared in this scope
src/htmlreporter.cpp:22:47: error: ‘insertHist’ was not declared in this scope
 void HtmlReporter::setInsertHist(atomic_long* insertHist, int insertSizePeak) {
                                               ^~~~~~~~~~
src/htmlreporter.cpp:22:47: note: suggested alternative: ‘sys_errlist’
 void HtmlReporter::setInsertHist(atomic_long* insertHist, int insertSizePeak) {
                                               ^~~~~~~~~~
                                               sys_errlist
src/htmlreporter.cpp:22:59: error: expected primary-expression before ‘int’
 void HtmlReporter::setInsertHist(atomic_long* insertHist, int insertSizePeak) {
                                                           ^~~
src/htmlreporter.cpp: In member function ‘void HtmlReporter::reportInsertSize(std::ofstream&, int)’:
src/htmlreporter.cpp:219:21: error: ‘mInsertHist’ was not declared in this scope
         allCount += mInsertHist[i];
                     ^~~~~~~~~~~
src/htmlreporter.cpp:219:21: note: suggested alternative: ‘setInsertHist’
         allCount += mInsertHist[i];
                     ^~~~~~~~~~~
                     setInsertHist
src/htmlreporter.cpp:221:17: error: ‘mInsertHist’ was not declared in this scope
     allCount += mInsertHist[mOptions->insertSizeMax];
                 ^~~~~~~~~~~
src/htmlreporter.cpp:221:17: note: suggested alternative: ‘setInsertHist’
     allCount += mInsertHist[mOptions->insertSizeMax];
                 ^~~~~~~~~~~
                 setInsertHist
make: *** [Makefile:27: obj/htmlreporter.o] Error 1
```

Here's the g++ version used
```bash
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sfchen** [comment]
Thanks for your report. Bug fixed.
